In [1]:
import pandas as pd
import numpy as np

In [35]:
data = pd.read_csv('D:\PGDBA\Competitions\EXL-Acumen/Acumen_2019_Input.csv')
submit = pd.read_csv('D:\PGDBA\Competitions\EXL-Acumen\submit.csv')

In [36]:
data.head()

,UNIQUE_ID,Rev_17_GeoPod,Rev_17_B,Rev_17_C,Vol_17_GeoPod,Vol_17_B,Vol_17_C,Rev_17_GeoPod_Logistics,Rev_17_GeoPod_HR,Rev_17_GeoPod_Finance,...,Vol_16_GeoPod_Logistics,Vol_16_GeoPod_HR,Vol_16_GeoPod_Finance,Vol_16_D,Vol_16_E,Vol_16_F,Vol_16_G,Vol_16_H,Vol_16_I,Attrition_Flag
0,20,148458,648,0,1533,6,0,126,1816,146516,...,1,1461,57,457,0,0,2350,0,0,0
1,37,48797,0,0,294,0,0,209,897,47691,...,1,278,6,109,1,0,7,0,0,0
2,44,1875,0,0,7,0,0,380,0,1495,...,1,3,0,0,0,0,0,0,0,0
3,48,1009,0,0,8,0,0,0,219,791,...,0,6,1,0,0,0,0,0,0,0
4,72,9781,235,0,46,1,0,275,0,9507,...,1,39,0,245,0,0,0,0,0,0

In [37]:
data.Market_Segment.unique()

array(['Large Business', 'Small Business'], dtype=object)

In [38]:
len(np.intersect1d(data.UNIQUE_ID,submit.UNIQUE_ID))

0

In [39]:
submit['Attrition_Flag'] = None

In [40]:
all_data = data.append(submit, ignore_index = True)

In [41]:
print(len(data), len(submit), len(all_data))

14601 4000 18601

In [42]:
all_data[all_data['Attrition_Flag'].isnull()]

,UNIQUE_ID,Rev_17_GeoPod,Rev_17_B,Rev_17_C,Vol_17_GeoPod,Vol_17_B,Vol_17_C,Rev_17_GeoPod_Logistics,Rev_17_GeoPod_HR,Rev_17_GeoPod_Finance,...,Vol_16_GeoPod_Logistics,Vol_16_GeoPod_HR,Vol_16_GeoPod_Finance,Vol_16_D,Vol_16_E,Vol_16_F,Vol_16_G,Vol_16_H,Vol_16_I,Attrition_Flag
14601,23,1875.00,0.00,0,7,0,0,380.00,0.000000e+00,1495.00,...,1,5,0,0,0,0,0,0,0,None
14602,29,47282.47,0.00,0,359,0,0,167.29,2.549000e+02,46860.28,...,1,337,1,107,0,0,0,0,0,None
14603,52,13964.25,0.00,0,63,0,0,285.00,0.000000e+00,13679.25,...,1,68,0,3,0,0,0,0,0,None
14604,88,22782.48,0.00,0,155,0,0,159.60,4.539360e+03,18083.52,...,1,195,12,410,0,0,0,3,0,None
14605,134,3223.65,0.00,0,15,0,0,287.08,-5.680000e-14,2936.57,...,1,39,0,0,0,0,8,0,0,None
14606,163,52109.68,3016.00,12500,297,16,5,220.40,1.250640e+03,50638.64,...,2,283,3,422,0,0,1848,3,0,None
14607,190,2772.00,0.00,0,10,0,0,380.00,0.000000e+00,2392.00,...,1,8,0,0,0,0,0,0,0,None
14608,197,110088.36,0.00,0,689,0,0,156.56,3.232210e+04,77609.70,...,1,623,37,5,0,0,34,0,0,None
14609,267,1794.00,0.00,0,6,0,0,0.00,0.000000e+00,1794.00,...,0,6,0,0,0,0,0,0,0,None
14610,277,6976.64,0.00,0,33,0,0,274.75,0.000000e+00,6701.89,...,1,31,0,1,0,0,45,0,0,None
14611,282,82165.38,107.25,4600,876,1,2,125.40,8.345700e+02,81205.41,...,1,791,51,370,0,0,0,2,0,None
14612,364,75241.87,0.00,0,379,0,0,252.80,-1.170000e-11,74989.07,...,1,335,0,61,0,4,0,0,0,None
14613,422,19273.31,0.00,0,199,0,0,122.96,1.873500e+02,18963.00,...,1,149,1,136,0,0,0,0,0,None
14614,455,4865.00,0.00,0,17,0,0,380.00,0.000000e+00,4485.00,...,1,14,0,0,0,0,0,0,0,None
14615,460,4278.69,0.00,0,27,0,0,0.00,0.000000e+00,4278.69,...,0,12,0,0,0,0,0,0,0,None
14616,464,9297.55,0.00,0,53,0,0,218.23,6.650400e+02,8414.28,...,1,49,2,8,0,20,0,0,0,None
14617,472,24076.48,0.00,0,168,0,0,129.20,9.206580e+03,14740.70,...,1,185,25,185,0,63,1,5,0,None
14618,493,2093.00,0.00,0,7,0,0,0.00,0.000000e+00,2093.00,...,0,7,0,0,0,0,0,0,0,None
14619,511,1690.64,0.00,0,12,0,0,190.64,1.140000e-13,1500.00,...,1,47,4,0,0,4,0,0,0,None
14620,536,2473.00,0.00,0,9,0,0,380.00,0.000000e+00,2093.00,...,1,6,0,0,0,0,0,0,0,None
14621,559,12575.15,0.00,0,45,0,0,361.00,0.000000e+00,12214.15,...,1,43,0,6,0,0,0,0,0,None
14622,572,13818.70,690.00,0,220,1,0,100.40,5.253000e+02,13193.00,...,1,167,51,20,0,208,1,0,0,None
14623,629,3289.00,0.00,0,11,0,0,0.00,0.000000e+00,3289.00,...,0,12,0,0,0,0,0,0,0,None
14624,639,5394.53,0.00,0,55,0,0,126.33,-7.110000e-14,5268.20,...,1,52,0,11,0,0,12,0,0,None
14625,640,6762.40,0.00,0,29,0,0,304.00,0.000000e+00,6458.40,...,1,32,0,1,0,0,0,0,0,None
14626,692,21467.50,0.00,0,123,0,0,212.95,1.482470e+03,19772.08,...,1,116,3,12,0,0,0,0,0,None
14627,746,42003.60,276.25,0,166,1,0,323.00,0.000000e+00,41680.60,...,1,166,0,59,0,0,0,0,0,None
14628,753,29615.03,783.38,0,621,13,0,70.46,7.157700e+02,28828.80,...,1,580,100,750,0,0,0,0,0,None
14629,824,6061.00,0.00,0,21,0,0,380.00,0.000000e+00,5681.00,...,1,21,0,8,0,0,0,0,0,None
14630,831,2392.00,0.00,0,8,0,0,0.00,0.000000e+00,2392.00,...,0,7,0,0,0,0,0,0,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18571,9401518645,1794.00,0.00,0,6,0,0,0.00,0.000000e+00,1794.00,...,0,6,0,16,0,0,0,0,0,None
18572,9401521096,2392.00,0.00,0,8,0,0,0.00,0.000000e+00,2392.00,...,0,8,0,0,0,0,0,0,0,None
18573,9401522994,1495.00,0.00,0,5,0,0,0.00,0.000000e+00,1495.00,...,0,5,0,12,0,0,0,0,0,None
18574,9401523516,2473.00,0.00,0,9,0,0,380.00,0.000000e+00,2093.00,...,1,7,0,9,0,2,0,0,0,None
18575,9401523530,7257.00,0.00,0,25,0,0,380.00,0.000000e+00,6877.00,...,1,17,0,0,0,0,0,0,0,None
18576,9401523939,1875.00,0.00,0,7,0,0,380.00,0.000000e+00,1495.00,...,0,3,0,0,0,0,0,0,0,None
18577,9401523951,5164.00,0.00,0,18,0,0,380.00,0.000000e+00,4784.00,...,1,16,0,13,0,0,0,0,0,None
18578,9401525183,2392.00,0.00,0,8,0,0,0.00,0.000000e+00,2392.00,...,0,8,0,0,0,0,0,0,0,None
18579,9401527451,8453.00,0.00,0,29,0,0,380.00,0.000000e+00,8073.00,...,1,7,0,9,0,0,0,0,0,None
18580,9401528409,1495.00,0.00,0,5,0,0,0.00,0.000000e+00,1495.00,...,0,5,0,0,0,0,0,0,0,None
18581,9401529099,2691.00,0.00,0,9,0,0,0.00,0.000000e+00,2691.00,...,0,10,0,1,0,0,0,0,0,None
18582,9401530050,2093.00,0.00,0,7,0,0,0.00,0.000000e+00,2093.00,...,0,8,0,10,0,0,0,0,0,None
18583,9401532245,3887.00,0.00,0,13,0,0,0.00,0.000000e+00,3887.00,...,0,11,0,14,8,0,0,0,0,None
18584,9401534497,1495.00,0.00,0,5,0,0,0.00,0.000000e+00,1495.00,...,0,5,0,0,0,0,0,0,0,None
18585,9401538533,2691.00,0.00,0,9,0,0,0.00,0.000000e+00,2691.00,...,0,8,0,18,0,0,0,0,0,None
18586,9401541094,1794.00,0.00,0,6,0,0,0.00,0.000000e+00,1794.00,...,0,9,0,34,0,0,0,0,0,None
18587,9401548699,15330.00,0.00,0,52,0,0,380.00,0.000000e+00,14950.00,...,0,1,0,59,0,0,0,0,0,None
18588,9401555637,1495.00,0.00,0,5,0,0,0.00,0.000000e+00,1495.00,...,0,1,0,3,1,0,0,0,0,None
18589,9401558450,1495.00,0.00,0,5,0,0,0.00,0.000000e+00,1495.00,...,0,4,0,0,0,0,0,0,0,None
18590,9401559014,1794.00,0.00,0,6,0,0,0.00,0.000000e+00,1794.00,...,0,2,0,6,0,0,0,0,0,None
18591,9401560656,1495.00,0.00,0,5,0,0,0.00,0.000000e+00,1495.00,...,0,4,0,0,0,0,0,0,0,None
18592,9401570190,4186.00,0.00,0,14,0,0,0.00,0.000000e+00,4186.00,...,0,14,0,0,0,0,0,0,0,None
18593,9401572168,1576.00,0.00,0,6,0,0,380.00,0.000000e+00,1196.00,...,1,0,0,0,0,0,0,0,0,None
18594,9401573946,1576.00,0.00,0,6,0,0,380.00,0.000000e+00,1196.00,...,0,1,0,0,0,0,0,0,0,None
18595,9401575614,2093.00,0.00,0,7,0,0,0.00,0.000000e+00,2093.00,...,0,6,0,2,0,0,0,0,0,None
18596,9401576709,2691.00,0.00,0,9,0,0,0.00,0.000000e+00,2691.00,...,0,9,0,0,0,0,0,0,0,None
18597,9401576978,7475.00,0.00,0,25,0,0,0.00,0.000000e+00,7475.00,...,0,4,0,0,0,0,0,0,0,None
18598,9401577485,1794.00,0.00,0,6,0,0,0.00,0.000000e+00,1794.00,...,0,8,0,0,0,0,0,0,0,None
18599,9401578730,2093.00,0.00,0,7,0,0,0.00,0.000000e+00,2093.00,...,0,1,0,0,0,0,0,0,0,None
18600,9401581749,2093.00,0.00,0,7,0,0,0.00,0.000000e+00,2093.00,...,0,2,0,0,0,0,0,0,0,None

In [43]:
all_data['Market_Segment'] = ['1' if x == 'Large Business' else 0 for x in all_data['Market_Segment']]
all_data['Market_Segment'] = all_data['Market_Segment'].astype('int32')

In [44]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18601 entries, 0 to 18600
Data columns (total 62 columns):
UNIQUE_ID                        18601 non-null int64
Rev_17_GeoPod                    18601 non-null float64
Rev_17_B                         18601 non-null float64
Rev_17_C                         18601 non-null int64
Vol_17_GeoPod                    18601 non-null int64
Vol_17_B                         18601 non-null int64
Vol_17_C                         18601 non-null int64
Rev_17_GeoPod_Logistics          18601 non-null float64
Rev_17_GeoPod_HR                 18601 non-null float64
Rev_17_GeoPod_Finance            18601 non-null float64
Vol_17_GeoPod_Logistics          18601 non-null int64
Vol_17_GeoPod_HR                 18601 non-null int64
Vol_17_GeoPod_Finance            18601 non-null int64
Vol_17_Death_Event               18601 non-null int64
Vol_17_Birth_Event               18601 non-null int64
Vol_17_COA                       18601 non-null int64
Vol_17_COA_Win                   18601 non-null int64
Rev_17_D                         18601 non-null float64
Rev_17_E                         18601 non-null float64
Rev_17_F                         18601 non-null float64
Rev_17_G                         18601 non-null int64
Rev_17_H                         18601 non-null float64
Rev_17_I                         18601 non-null float64
Vol_17_D                         18601 non-null int64
Vol_17_E                         18601 non-null int64
Vol_17_F                         18601 non-null int64
Vol_17_G                         18601 non-null int64
Vol_17_H                         18601 non-null int64
Vol_17_I                         18601 non-null int64
Ind_2013_pushback                18601 non-null int64
Ind_2014_pushback                18601 non-null int64
Ind_2015_pushback                18601 non-null int64
Ind_2016_pushback                18601 non-null int64
Ind_2017_pushback                18601 non-null int64
DataCorp_Market_Share            12294 non-null float64
Major_competitor_market_share    12294 non-null float64
Other_competitor_market_share    12294 non-null float64
Tenure_months                    16445 non-null float64
Market_Segment                   18601 non-null int32
Sub_Segment                      17357 non-null object
Sales_Person_Jun_17              18601 non-null object
RSM_Jun_17                       18601 non-null object
Director_Jun_17                  18601 non-null object
VP_Jun_17                        18601 non-null object
Sales_Person_Dec_17              18601 non-null object
RSM_Dec_17                       18601 non-null object
Director_Dec_17                  18601 non-null object
VP_Dec_17                        18601 non-null object
Discount_17                      18601 non-null float64
Count_Entities                   18597 non-null float64
Count_Jurisdicion                18597 non-null float64
Price_Point                      18601 non-null float64
Vol_16_GeoPod_Logistics          18601 non-null int64
Vol_16_GeoPod_HR                 18601 non-null int64
Vol_16_GeoPod_Finance            18601 non-null int64
Vol_16_D                         18601 non-null int64
Vol_16_E                         18601 non-null int64
Vol_16_F                         18601 non-null int64
Vol_16_G                         18601 non-null int64
Vol_16_H                         18601 non-null int64
Vol_16_I                         18601 non-null int64
Attrition_Flag                   14601 non-null object
dtypes: float64(18), int32(1), int64(33), object(10)
memory usage: 8.7+ MB

In [45]:
all_data.Sub_Segment.unique()

array(['Multinational Banks', 'Credit Unions', 'Small Business',
       'Investment Firms', nan], dtype=object)

In [46]:
all_data['Sub_Segment'] = ['1' if x == 'Small Business' else x for x in all_data['Sub_Segment']]
all_data['Sub_Segment'] = ['2' if x == 'Investment Firms' else x for x in all_data['Sub_Segment']]
all_data['Sub_Segment'] = ['3' if x == 'Credit Unions' else x for x in all_data['Sub_Segment']]
all_data['Sub_Segment'] = ['4' if x == 'Multinational Banks' else x for x in all_data['Sub_Segment']]
all_data['Sub_Segment'].fillna(0, inplace = True)
all_data['Sub_Segment'] = all_data['Sub_Segment'].astype('int32')

In [47]:
all_data['Sales_Person_Jun_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['Sales_Person_Jun_17']]
all_data['Sales_Person_Jun_17'] = all_data['Sales_Person_Jun_17'].astype('int32')

all_data['RSM_Jun_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['RSM_Jun_17']]
all_data['RSM_Jun_17'] = all_data['RSM_Jun_17'].astype('int32')

all_data['Director_Jun_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['Director_Jun_17']]
all_data['Director_Jun_17'] = all_data['Director_Jun_17'].astype('int32')

all_data['VP_Jun_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['VP_Jun_17']]
all_data['VP_Jun_17'] = all_data['VP_Jun_17'].astype('int32')

all_data['Sales_Person_Dec_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['Sales_Person_Dec_17']]
all_data['Sales_Person_Dec_17'] = all_data['Sales_Person_Dec_17'].astype('int32')

all_data['RSM_Dec_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['RSM_Dec_17']]
all_data['RSM_Dec_17'] = all_data['RSM_Dec_17'].astype('int32')

all_data['Director_Dec_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['Director_Dec_17']]
all_data['Director_Dec_17'] = all_data['Director_Dec_17'].astype('int32')

all_data['VP_Dec_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['VP_Dec_17']]
all_data['VP_Dec_17'] = all_data['VP_Dec_17'].astype('int32')

In [48]:
min(all_data['Rev_17_GeoPod']), max(all_data['Rev_17_GeoPod'])

(306.0, 538716.0)

In [58]:
all_data.isnull().sum()

UNIQUE_ID                           0
Rev_17_GeoPod                       0
Rev_17_B                            0
Rev_17_C                            0
Vol_17_GeoPod                       0
Vol_17_B                            0
Vol_17_C                            0
Rev_17_GeoPod_Logistics             0
Rev_17_GeoPod_HR                    0
Rev_17_GeoPod_Finance               0
Vol_17_GeoPod_Logistics             0
Vol_17_GeoPod_HR                    0
Vol_17_GeoPod_Finance               0
Vol_17_Death_Event                  0
Vol_17_Birth_Event                  0
Vol_17_COA                          0
Vol_17_COA_Win                      0
Rev_17_D                            0
Rev_17_E                            0
Rev_17_F                            0
Rev_17_G                            0
Rev_17_H                            0
Rev_17_I                            0
Vol_17_D                            0
Vol_17_E                            0
Vol_17_F                            0
Vol_17_G                            0
Vol_17_H                            0
Vol_17_I                            0
Ind_2013_pushback                   0
                                 ...
Ind_2016_pushback                   0
Ind_2017_pushback                   0
DataCorp_Market_Share            6307
Major_competitor_market_share    6307
Other_competitor_market_share    6307
Tenure_months                    2156
Market_Segment                      0
Sub_Segment                         0
Sales_Person_Jun_17                 0
RSM_Jun_17                          0
Director_Jun_17                     0
VP_Jun_17                           0
Sales_Person_Dec_17                 0
RSM_Dec_17                          0
Director_Dec_17                     0
VP_Dec_17                           0
Discount_17                         0
Count_Entities                      4
Count_Jurisdicion                   4
Price_Point                         0
Vol_16_GeoPod_Logistics             0
Vol_16_GeoPod_HR                    0
Vol_16_GeoPod_Finance               0
Vol_16_D                            0
Vol_16_E                            0
Vol_16_F                            0
Vol_16_G                            0
Vol_16_H                            0
Vol_16_I                            0
Attrition_Flag                   4000
Length: 62, dtype: int64

In [70]:
all_data.DataCorp_Market_Share.unique()
all_data['DataCorp_Market_Share'].fillna(np.mean(all_data.DataCorp_Market_Share), inplace = True)

In [72]:
all_data['Major_competitor_market_share'].fillna(round(np.mean(all_data.Major_competitor_market_share),2), inplace = True)
all_data.Major_competitor_market_share.unique()

array([0.        , 0.05204246, 1.        , 0.02      , 0.87      ,
       0.34      , 0.01      , 0.03      , 0.67      , 0.1       ,
       0.88      , 0.42      , 0.2       , 0.08      , 0.04      ,
       0.64      , 0.81      , 0.05      , 0.94      , 0.14      ,
       0.15      , 0.09      , 0.19      , 0.84      , 0.69      ,
       0.29      , 0.12      , 0.06      , 0.38      , 0.41      ,
       0.82      , 0.5       , 0.21      , 0.79      , 0.13      ,
       0.18      , 0.83      , 0.95      , 0.33      , 0.26      ,
       0.4       , 0.25      , 0.17      , 0.11      , 0.27      ,
       0.31      , 0.52      , 0.45      , 0.77      , 0.65      ,
       0.91      , 0.63      , 0.62      , 0.39      , 0.07      ,
       0.93      , 0.73      , 0.37      , 0.68      , 0.55      ,
       0.57      , 0.16      , 0.76      , 0.43      , 0.56      ,
       0.9       , 0.32      , 0.96      , 0.74      , 0.47      ,
       0.92      , 0.46      , 0.75      , 0.8       , 0.89      ,
       0.36      , 0.59      , 0.22      , 0.3       , 0.85      ,
       0.23      , 0.44      , 0.86      , 0.6       , 0.71      ,
       0.51      , 0.58      , 0.72      , 0.24      , 0.54      ,
       0.7       , 0.78      ])

In [73]:
all_data['Other_competitor_market_share'].fillna(round(np.mean(all_data.Other_competitor_market_share),2), inplace = True)
all_data.Other_competitor_market_share.unique()

array([0.  , 0.14, 1.  , 0.5 , 0.13, 0.17, 0.04, 0.07, 0.25, 0.33, 0.16,
       0.2 , 0.01, 0.06, 0.32, 0.15, 0.02, 0.29, 0.09, 0.05, 0.48, 0.35,
       0.11, 0.69, 0.03, 0.27, 0.12, 0.08, 0.39, 0.95, 0.19, 0.79, 0.18,
       0.22, 0.71, 0.4 , 0.7 , 0.1 , 0.21, 0.97, 0.28, 0.43, 0.23, 0.51,
       0.57, 0.54, 0.26, 0.82, 0.88, 0.42, 0.3 , 0.36, 0.38, 0.73, 0.55,
       0.6 , 0.75, 0.45, 0.56, 0.31, 0.24, 0.44, 0.94, 0.47, 0.34, 0.89,
       0.78, 0.91, 0.67, 0.59, 0.41, 0.37, 0.62, 0.49, 0.52, 0.9 , 0.86,
       0.65, 0.81, 0.53, 0.46, 0.92, 0.96, 0.84, 0.74, 0.64, 0.76, 0.99,
       0.8 , 0.83, 0.68, 0.63, 0.72, 0.58, 0.85, 0.77, 0.93, 0.98, 0.66,
       0.87])

In [74]:
all_data['Tenure_months'].fillna(round(np.mean(all_data.Tenure_months),2), inplace = True)
all_data.Tenure_months.unique()

array([107.  , 200.  ,  24.  ,  77.  ,  58.  , 133.  ,  80.  ,  88.  ,
       287.  ,  22.  , 265.  , 255.  ,  92.  ,  83.  , 168.  ,  97.  ,
       267.  , 127.  , 138.  , 105.56,  19.  ,  38.  , 245.  ,  69.  ,
       125.  , 152.  ,  42.  , 141.  ,  71.  ,  46.  ,  14.  ,  99.  ,
       158.  ,  59.  ,  26.  , 118.  ,  34.  , 140.  ,  52.  , 105.  ,
       224.  , 273.  , 144.  ,  21.  ,  95.  ,  72.  , 191.  , 196.  ,
        90.  ,  75.  ,  85.  , 176.  , 157.  , 109.  ,  31.  , 112.  ,
       155.  , 135.  ,  43.  ,  13.  ,  87.  , 208.  ,  20.  , 270.  ,
       220.  ,  78.  , 281.  ,  54.  ,  45.  ,  28.  ,  16.  , 237.  ,
        15.  , 154.  ,  35.  ,  23.  , 104.  ,  74.  , 207.  , 195.  ,
        49.  , 156.  ,  32.  , 172.  , 258.  , 249.  ,  48.  ,  17.  ,
        18.  , 266.  ,  68.  , 192.  , 161.  , 120.  , 148.  , 142.  ,
       239.  , 165.  , 198.  ,  36.  , 212.  , 121.  , 114.  ,  70.  ,
       131.  ,  84.  , 111.  , 217.  , 174.  , 234.  , 240.  , 117.  ,
       194.  , 119.  ,  63.  , 233.  ,  60.  , 129.  , 145.  ,  94.  ,
       115.  ,  96.  , 143.  ,  66.  , 110.  , 278.  , 279.  , 188.  ,
        33.  ,  73.  ,  61.  , 180.  ,  62.  ,  64.  , 231.  , 268.  ,
       253.  , 108.  , 136.  ,  37.  , 203.  , 116.  , 221.  ,  40.  ,
       284.  ,  29.  , 206.  , 166.  , 197.  , 169.  , 285.  , 227.  ,
       277.  , 139.  ,  47.  , 248.  , 238.  , 122.  , 216.  , 150.  ,
       102.  ,  89.  ,  51.  ,  39.  , 223.  , 222.  ,  93.  , 177.  ,
       283.  , 256.  , 167.  , 185.  , 275.  , 182.  , 101.  , 219.  ,
       181.  , 210.  , 162.  , 124.  , 262.  , 171.  , 193.  , 184.  ,
       153.  ,  55.  , 215.  ,  57.  , 269.  , 190.  , 205.  , 201.  ,
       151.  ,  56.  , 236.  , 130.  ,  91.  , 218.  , 286.  , 159.  ,
       214.  ,  76.  ,  81.  , 251.  , 147.  , 259.  ,  53.  , 229.  ,
        82.  , 242.  , 163.  , 230.  , 178.  ,  41.  , 282.  , 250.  ,
       254.  ,  30.  , 209.  , 160.  , 247.  ,  25.  ,  86.  ,  50.  ,
       246.  , 252.  , 241.  , 134.  , 146.  ,  44.  ,  27.  , 179.  ,
       232.  , 123.  , 199.  ,  67.  , 261.  ,  79.  , 137.  , 264.  ,
       225.  , 243.  , 189.  , 149.  , 100.  , 164.  , 175.  , 276.  ,
       173.  , 186.  , 204.  , 280.  , 263.  , 272.  , 106.  , 260.  ,
       113.  , 202.  , 211.  , 235.  , 132.  , 187.  , 170.  , 271.  ,
       103.  , 226.  , 257.  ,  98.  , 244.  , 126.  , 128.  , 274.  ,
       183.  , 228.  ,  12.  , 213.  ,  65.  ])

In [76]:
all_data['Count_Entities'].fillna(round(np.mean(all_data.Count_Entities),2), inplace = True)
all_data.Count_Entities.unique()

array([1.450e+02, 3.200e+01, 1.000e+00, 8.000e+00, 2.000e+00, 1.500e+01,
       2.400e+01, 1.200e+01, 9.000e+00, 5.000e+01, 7.000e+00, 3.000e+00,
       9.100e+01, 1.470e+02, 3.170e+02, 2.070e+02, 2.300e+01, 5.300e+01,
       1.000e+01, 2.200e+01, 2.800e+01, 4.100e+01, 5.700e+01, 7.100e+01,
       8.100e+01, 1.400e+01, 5.900e+01, 2.000e+01, 6.100e+01, 7.800e+01,
       4.200e+01, 2.700e+01, 1.420e+02, 1.700e+01, 2.100e+01, 6.000e+00,
       1.960e+02, 4.000e+00, 5.000e+00, 3.300e+01, 1.300e+01, 6.200e+01,
       1.600e+01, 5.100e+01, 4.800e+01, 4.400e+01, 6.400e+01, 3.000e+01,
       5.400e+01, 1.970e+02, 1.100e+01, 1.800e+01, 1.419e+03, 1.010e+02,
       1.070e+02, 6.700e+01, 4.000e+01, 2.900e+01, 3.900e+01, 6.100e+02,
       1.050e+02, 1.520e+02, 1.860e+02, 1.190e+02, 2.500e+01, 7.600e+01,
       1.560e+02, 4.900e+01, 3.100e+01, 1.700e+02, 3.700e+01, 7.700e+01,
       1.360e+02, 1.353e+03, 2.090e+02, 2.600e+01, 6.900e+01, 4.500e+01,
       5.600e+01, 1.660e+02, 9.200e+01, 2.820e+02, 8.000e+01, 5.180e+02,
       5.800e+01, 2.980e+02, 5.500e+02, 7.900e+01, 1.530e+02, 7.200e+01,
       8.500e+01, 8.900e+01, 4.600e+01, 2.170e+02, 3.240e+02, 1.840e+02,
       1.060e+02, 2.280e+02, 1.490e+02, 1.710e+02, 9.900e+01, 5.200e+01,
       9.500e+01, 8.300e+01, 3.800e+01, 2.360e+02, 3.400e+01, 2.370e+02,
       3.950e+02, 7.500e+01, 3.600e+01, 7.300e+01, 6.500e+01, 1.110e+02,
       4.770e+02, 5.280e+02, 1.890e+02, 2.480e+02, 1.900e+01, 6.060e+02,
       1.864e+03, 2.740e+02, 2.710e+02, 1.290e+02, 3.920e+02, 1.280e+02,
       3.500e+01, 6.300e+01, 9.600e+01, 3.000e+02, 1.650e+02, 4.260e+02,
       1.319e+03, 3.150e+02, 2.340e+02, 5.330e+02, 7.790e+02, 5.300e+02,
       6.800e+01, 1.040e+02, 1.160e+02, 9.700e+01, 6.600e+01, 4.300e+01,
       4.700e+01, 1.540e+02, 3.560e+02, 8.700e+01, 1.184e+03, 9.910e+02,
       1.480e+02, 1.340e+02, 1.210e+02, 5.770e+02, 8.780e+02, 1.430e+02,
       1.370e+02, 2.840e+02, 2.730e+02, 6.000e+01, 1.120e+02, 8.400e+01,
       5.500e+01, 1.910e+02, 6.230e+02, 1.000e+02, 1.020e+02, 9.300e+01,
       1.030e+02, 2.850e+02, 2.320e+02, 1.338e+03, 9.800e+01, 2.905e+03,
       1.080e+02, 8.800e+01, 1.330e+02, 2.600e+02, 2.860e+02, 1.170e+02,
       1.300e+02, 4.020e+02, 1.830e+02, 5.530e+02, 1.760e+02, 3.440e+02,
       1.440e+02, 4.570e+02, 1.390e+02, 1.100e+02, 1.400e+02, 9.890e+02,
       1.620e+02, 1.570e+02, 2.131e+01, 1.130e+02, 1.150e+02, 1.900e+03,
       2.680e+02, 6.950e+02, 1.260e+02, 4.730e+02, 2.200e+02, 1.920e+02,
       1.800e+02, 1.230e+03, 9.000e+01, 2.510e+02, 7.730e+02, 4.140e+02,
       9.400e+01, 2.210e+02, 2.930e+02, 2.010e+02, 2.130e+02, 4.630e+02,
       2.520e+02, 1.930e+02, 1.630e+02, 2.100e+02, 6.930e+02, 5.480e+02,
       1.900e+02, 2.570e+02, 1.460e+02, 1.220e+02, 4.490e+02, 2.180e+02,
       8.210e+02, 6.480e+02, 1.670e+02, 3.010e+02, 4.950e+02, 1.350e+02,
       1.640e+02, 2.940e+02, 2.000e+02, 1.730e+02, 1.600e+02, 2.060e+02,
       2.040e+02, 2.380e+02, 1.720e+02, 1.200e+02, 7.850e+02, 3.900e+02,
       1.070e+03, 2.990e+02, 1.549e+03, 1.756e+03, 1.396e+03, 1.850e+02,
       3.120e+02, 4.520e+02, 4.910e+02, 3.180e+02, 5.370e+02, 1.239e+03,
       1.230e+02, 1.880e+02, 4.510e+02, 5.150e+02, 5.080e+02, 5.850e+02,
       3.540e+02, 3.870e+02, 6.370e+02, 2.760e+02, 1.580e+02, 3.840e+02,
       4.030e+02, 2.310e+02, 1.680e+02, 1.790e+02, 6.140e+02, 3.860e+02,
       2.160e+03, 1.140e+02, 1.950e+02, 3.820e+02, 1.810e+02, 1.036e+03,
       1.270e+02, 1.380e+02, 1.820e+02, 1.500e+02, 2.220e+02, 2.230e+02,
       9.850e+02, 8.200e+01, 2.910e+02, 7.670e+02, 2.410e+02, 4.010e+02,
       7.400e+01, 4.460e+02, 8.600e+01, 3.230e+02, 1.034e+03, 3.330e+02,
       5.460e+02, 6.760e+02, 9.550e+02, 5.580e+02, 5.660e+02, 4.540e+02,
       1.980e+02, 8.850e+02, 9.630e+02, 1.310e+02, 5.290e+02, 4.320e+02,
       7.940e+02, 6.250e+02, 5.250e+02, 3.250e+02, 2.160e+02, 2.110e+02,
       3.720e+02, 3.080e+02, 2.790e+02, 3.110e+02, 4.360e+02, 4.390e+02,
       2.150e+02, 7.740e+02, 1.775e+03, 2.300e+02, 1.550e+02, 1.250e+02,
       1.320e+02, 1.990e+02, 8.660e+02, 2.720e+02, 2.240e+02, 2.970e+02,
       1.090e+02, 3.730e+02, 2.290e+02, 2.870e+02, 7.000e+01, 1.770e+02,
       3.520e+02, 8.420e+02, 4.170e+02, 2.450e+02, 2.460e+02, 2.440e+02,
       1.708e+03, 1.740e+02, 3.460e+02, 3.670e+02, 1.940e+02, 5.830e+02,
       1.510e+02, 8.700e+02, 1.750e+02, 2.920e+02, 1.410e+02, 2.580e+02,
       1.240e+02, 8.360e+02, 5.960e+02, 3.510e+02, 2.250e+02, 3.680e+02,
       6.590e+02, 4.220e+02, 3.270e+02, 4.900e+02, 2.190e+02, 2.750e+02,
       6.490e+02, 2.350e+02, 9.870e+02, 1.180e+02, 1.590e+02, 2.390e+02,
       2.540e+02, 2.660e+02, 5.710e+02, 1.293e+03, 3.530e+02, 3.220e+02,
       7.320e+02, 2.683e+03, 9.960e+02, 3.090e+02, 1.537e+03, 2.890e+02,
       4.940e+02, 4.650e+02, 5.560e+02, 2.610e+02, 4.305e+03, 8.880e+02,
       6.560e+02, 4.920e+02, 5.120e+02, 7.570e+02, 4.760e+02, 2.500e+02,
       2.880e+02, 2.630e+02, 2.470e+02, 3.550e+02, 3.910e+02, 3.800e+02,
       3.280e+02, 3.480e+02, 2.960e+02, 7.510e+02, 7.410e+02, 4.180e+02,
       3.850e+02, 2.620e+02, 1.379e+03, 3.380e+02, 3.230e+03, 2.780e+02,
       2.260e+02, 5.680e+02, 3.740e+02, 1.150e+03, 4.970e+02, 5.230e+02,
       2.080e+02, 1.870e+02, 2.830e+02, 3.420e+02, 3.210e+02])

In [77]:
all_data['Count_Jurisdicion'].fillna(round(np.mean(all_data.Count_Jurisdicion),2), inplace = True)
all_data.Count_Jurisdicion.unique()

array([51.  , 49.  ,  6.  ,  7.  , 30.  ,  8.  , 50.  , 16.  ,  4.  ,
       48.  ,  5.  ,  3.  , 41.  , 31.  , 47.  , 18.  , 44.  , 25.  ,
       22.  , 23.  , 40.  , 24.  , 43.  , 35.  , 39.  , 19.  ,  9.  ,
       37.  , 38.  , 17.  , 42.  ,  2.  , 36.  , 10.  , 26.  , 28.  ,
       13.  , 46.  , 12.  , 45.  , 21.  , 14.  , 27.  ,  1.  , 32.  ,
       15.  , 20.  , 11.  , 33.  , 29.  , 34.  , 13.94])

In [92]:
#all_data['Attrition_Flag'] = all_data['Attrition_Flag'].astype('int32')

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [91]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18601 entries, 0 to 18600
Data columns (total 62 columns):
UNIQUE_ID                        18601 non-null int64
Rev_17_GeoPod                    18601 non-null float64
Rev_17_B                         18601 non-null float64
Rev_17_C                         18601 non-null int64
Vol_17_GeoPod                    18601 non-null int64
Vol_17_B                         18601 non-null int64
Vol_17_C                         18601 non-null int64
Rev_17_GeoPod_Logistics          18601 non-null float64
Rev_17_GeoPod_HR                 18601 non-null float64
Rev_17_GeoPod_Finance            18601 non-null float64
Vol_17_GeoPod_Logistics          18601 non-null int64
Vol_17_GeoPod_HR                 18601 non-null int64
Vol_17_GeoPod_Finance            18601 non-null int64
Vol_17_Death_Event               18601 non-null int64
Vol_17_Birth_Event               18601 non-null int64
Vol_17_COA                       18601 non-null int64
Vol_17_COA_Win                   18601 non-null int64
Rev_17_D                         18601 non-null float64
Rev_17_E                         18601 non-null float64
Rev_17_F                         18601 non-null float64
Rev_17_G                         18601 non-null int64
Rev_17_H                         18601 non-null float64
Rev_17_I                         18601 non-null float64
Vol_17_D                         18601 non-null int64
Vol_17_E                         18601 non-null int64
Vol_17_F                         18601 non-null int64
Vol_17_G                         18601 non-null int64
Vol_17_H                         18601 non-null int64
Vol_17_I                         18601 non-null int64
Ind_2013_pushback                18601 non-null int64
Ind_2014_pushback                18601 non-null int64
Ind_2015_pushback                18601 non-null int64
Ind_2016_pushback                18601 non-null int64
Ind_2017_pushback                18601 non-null int64
DataCorp_Market_Share            18601 non-null float64
Major_competitor_market_share    18601 non-null float64
Other_competitor_market_share    18601 non-null float64
Tenure_months                    18601 non-null float64
Market_Segment                   18601 non-null int32
Sub_Segment                      18601 non-null int32
Sales_Person_Jun_17              18601 non-null int32
RSM_Jun_17                       18601 non-null int32
Director_Jun_17                  18601 non-null int32
VP_Jun_17                        18601 non-null int32
Sales_Person_Dec_17              18601 non-null int32
RSM_Dec_17                       18601 non-null int32
Director_Dec_17                  18601 non-null int32
VP_Dec_17                        18601 non-null int32
Discount_17                      18601 non-null float64
Count_Entities                   18601 non-null float64
Count_Jurisdicion                18601 non-null float64
Price_Point                      18601 non-null float64
Vol_16_GeoPod_Logistics          18601 non-null int64
Vol_16_GeoPod_HR                 18601 non-null int64
Vol_16_GeoPod_Finance            18601 non-null int64
Vol_16_D                         18601 non-null int64
Vol_16_E                         18601 non-null int64
Vol_16_F                         18601 non-null int64
Vol_16_G                         18601 non-null int64
Vol_16_H                         18601 non-null int64
Vol_16_I                         18601 non-null int64
Attrition_Flag                   14601 non-null object
dtypes: float64(18), int32(10), int64(33), object(1)
memory usage: 8.1+ MB

# Training the model

In [53]:
from catboost import CatBoostClassifier,Pool, cv
from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold,train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score

In [94]:
df_train=all_data[all_data['Attrition_Flag'].isnull()==False].copy()
df_test=all_data[all_data['Attrition_Flag'].isnull()==True].copy()

df_train['Attrition_Flag'] = df_train['Attrition_Flag'].astype('int32')
print(df_train.shape,df_test.shape)

(14601, 62) (4000, 62)

In [95]:
X,y=df_train.drop(['UNIQUE_ID','Attrition_Flag'],axis=1),df_train['Attrition_Flag']
Xtest=df_test.drop(['UNIQUE_ID','Attrition_Flag'],axis=1)

#X = X.fillna(0)
#Xtest = Xtest.fillna(0)
print(X.shape,Xtest.shape)
X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=0.20,random_state = 1994,stratify=y)

(14601, 60) (4000, 60)

In [96]:
X.isnull().sum()

Rev_17_GeoPod                    0
Rev_17_B                         0
Rev_17_C                         0
Vol_17_GeoPod                    0
Vol_17_B                         0
Vol_17_C                         0
Rev_17_GeoPod_Logistics          0
Rev_17_GeoPod_HR                 0
Rev_17_GeoPod_Finance            0
Vol_17_GeoPod_Logistics          0
Vol_17_GeoPod_HR                 0
Vol_17_GeoPod_Finance            0
Vol_17_Death_Event               0
Vol_17_Birth_Event               0
Vol_17_COA                       0
Vol_17_COA_Win                   0
Rev_17_D                         0
Rev_17_E                         0
Rev_17_F                         0
Rev_17_G                         0
Rev_17_H                         0
Rev_17_I                         0
Vol_17_D                         0
Vol_17_E                         0
Vol_17_F                         0
Vol_17_G                         0
Vol_17_H                         0
Vol_17_I                         0
Ind_2013_pushback                0
Ind_2014_pushback                0
Ind_2015_pushback                0
Ind_2016_pushback                0
Ind_2017_pushback                0
DataCorp_Market_Share            0
Major_competitor_market_share    0
Other_competitor_market_share    0
Tenure_months                    0
Market_Segment                   0
Sub_Segment                      0
Sales_Person_Jun_17              0
RSM_Jun_17                       0
Director_Jun_17                  0
VP_Jun_17                        0
Sales_Person_Dec_17              0
RSM_Dec_17                       0
Director_Dec_17                  0
VP_Dec_17                        0
Discount_17                      0
Count_Entities                   0
Count_Jurisdicion                0
Price_Point                      0
Vol_16_GeoPod_Logistics          0
Vol_16_GeoPod_HR                 0
Vol_16_GeoPod_Finance            0
Vol_16_D                         0
Vol_16_E                         0
Vol_16_F                         0
Vol_16_G                         0
Vol_16_H                         0
Vol_16_I                         0
dtype: int64

In [99]:
err=[]
y_pred_tot=[]
from sklearn.model_selection import KFold,StratifiedKFold
fold=StratifiedKFold(n_splits=10,shuffle=True,random_state=1994)
i=1
#print(X.shape, y.shape)
#y.astype('int32')
#from sklearn.utils.multiclass import type_of_target
#print(type_of_target(y))
#a,b = fold.split(X,y)
for train_index, test_index in fold.split(X,y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    m=LGBMClassifier(n_estimators=1000,random_state=1994,learning_rate=0.08,colsample_bytree=0.2,objective='binary',scale_pos_weight=1)
    m.fit(X_train,y_train,eval_set=[(X_test, y_test)],eval_metric='auc', early_stopping_rounds=200,verbose=200)
    preds=m.predict_proba(X_test)[:,-1]
    print("err: ",roc_auc_score(y_test,preds))
    err.append(roc_auc_score(y_test,preds))
    p = m.predict_proba(Xtest)[:,-1]
    i=i+1
    y_pred_tot.append(p)

Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.865039	valid_0's binary_logloss: 0.266481
Early stopping, best iteration is:
[162]	valid_0's auc: 0.865794	valid_0's binary_logloss: 0.265132
err:  0.8657938013915243
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.839359	valid_0's binary_logloss: 0.286277
Early stopping, best iteration is:
[101]	valid_0's auc: 0.841843	valid_0's binary_logloss: 0.283417
err:  0.841842715580856
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.840089	valid_0's binary_logloss: 0.290944
Early stopping, best iteration is:
[99]	valid_0's auc: 0.841541	valid_0's binary_logloss: 0.287787
err:  0.8415412186379928
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.863167	valid_0's binary_logloss: 0.268894
Early stopping, best iteration is:
[167]	valid_0's auc: 0.865355	valid_0's binary_logloss: 0.267491
err:  0.8653552603837235
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.859667	valid_0's binary_logloss: 0.273955
Early stopping, best iteration is:
[105]	valid_0's auc: 0.85661	valid_0's binary_logloss: 0.271751
err:  0.8566097406704618
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.873976	valid_0's binary_logloss: 0.259072
Early stopping, best iteration is:
[97]	valid_0's auc: 0.880746	valid_0's binary_logloss: 0.25744
err:  0.8807461579226284
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.862782	valid_0's binary_logloss: 0.266435
Early stopping, best iteration is:
[98]	valid_0's auc: 0.867483	valid_0's binary_logloss: 0.263287
err:  0.8674827103398532
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.861233	valid_0's binary_logloss: 0.267393
Early stopping, best iteration is:
[93]	valid_0's auc: 0.866672	valid_0's binary_logloss: 0.267246
err:  0.866672323815181
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.870052	valid_0's binary_logloss: 0.266105
Early stopping, best iteration is:
[161]	valid_0's auc: 0.871219	valid_0's binary_logloss: 0.26425
err:  0.8712185497899784
Training until validation scores don't improve for 200 rounds
[200]	valid_0's auc: 0.862578	valid_0's binary_logloss: 0.270667
Early stopping, best iteration is:
[184]	valid_0's auc: 0.863685	valid_0's binary_logloss: 0.270033
err:  0.863685349399635

In [100]:
np.mean(err,0)

0.8620947827931834